// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	sampleentity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSampleEntityUsecaseInterface is an autogenerated mock type for the SampleEntityUsecaseInterface type
type MockSampleEntityUsecaseInterface struct {
	mock.Mock
}

type MockSampleEntityUsecaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSampleEntityUsecaseInterface) EXPECT() *MockSampleEntityUsecaseInterface_Expecter {
	return &MockSampleEntityUsecaseInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sampEnt
func (_m *MockSampleEntityUsecaseInterface) Create(ctx context.Context, sampEnt *sampleentity.Sample) (*sampleentity.Sample, error) {
	ret := _m.Called(ctx, sampEnt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sampleentity.Sample
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sampleentity.Sample) (*sampleentity.Sample, error)); ok {
		return rf(ctx, sampEnt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sampleentity.Sample) *sampleentity.Sample); ok {
		r0 = rf(ctx, sampEnt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sampleentity.Sample)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sampleentity.Sample) error); ok {
		r1 = rf(ctx, sampEnt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSampleEntityUsecaseInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSampleEntityUsecaseInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sampEnt *sampleentity.Sample
func (_e *MockSampleEntityUsecaseInterface_Expecter) Create(ctx interface{}, sampEnt interface{}) *MockSampleEntityUsecaseInterface_Create_Call {
	return &MockSampleEntityUsecaseInterface_Create_Call{Call: _e.mock.On("Create", ctx, sampEnt)}
}

func (_c *MockSampleEntityUsecaseInterface_Create_Call) Run(run func(ctx context.Context, sampEnt *sampleentity.Sample)) *MockSampleEntityUsecaseInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sampleentity.Sample))
	})
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_Create_Call) Return(_a0 *sampleentity.Sample, _a1 error) *MockSampleEntityUsecaseInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_Create_Call) RunAndReturn(run func(context.Context, *sampleentity.Sample) (*sampleentity.Sample, error)) *MockSampleEntityUsecaseInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSampleEntityUsecaseInterface) Delete(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSampleEntityUsecaseInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSampleEntityUsecaseInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockSampleEntityUsecaseInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockSampleEntityUsecaseInterface_Delete_Call {
	return &MockSampleEntityUsecaseInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSampleEntityUsecaseInterface_Delete_Call) Run(run func(ctx context.Context, id uint64)) *MockSampleEntityUsecaseInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_Delete_Call) Return(_a0 error) *MockSampleEntityUsecaseInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_Delete_Call) RunAndReturn(run func(context.Context, uint64) error) *MockSampleEntityUsecaseInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockSampleEntityUsecaseInterface) List(ctx context.Context) ([]*sampleentity.Sample, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*sampleentity.Sample
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*sampleentity.Sample, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*sampleentity.Sample); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sampleentity.Sample)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSampleEntityUsecaseInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSampleEntityUsecaseInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSampleEntityUsecaseInterface_Expecter) List(ctx interface{}) *MockSampleEntityUsecaseInterface_List_Call {
	return &MockSampleEntityUsecaseInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSampleEntityUsecaseInterface_List_Call) Run(run func(ctx context.Context)) *MockSampleEntityUsecaseInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_List_Call) Return(_a0 []*sampleentity.Sample, _a1 error) *MockSampleEntityUsecaseInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_List_Call) RunAndReturn(run func(context.Context) ([]*sampleentity.Sample, error)) *MockSampleEntityUsecaseInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, sampEnt
func (_m *MockSampleEntityUsecaseInterface) Update(ctx context.Context, sampEnt *sampleentity.Sample) error {
	ret := _m.Called(ctx, sampEnt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sampleentity.Sample) error); ok {
		r0 = rf(ctx, sampEnt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSampleEntityUsecaseInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSampleEntityUsecaseInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sampEnt *sampleentity.Sample
func (_e *MockSampleEntityUsecaseInterface_Expecter) Update(ctx interface{}, sampEnt interface{}) *MockSampleEntityUsecaseInterface_Update_Call {
	return &MockSampleEntityUsecaseInterface_Update_Call{Call: _e.mock.On("Update", ctx, sampEnt)}
}

func (_c *MockSampleEntityUsecaseInterface_Update_Call) Run(run func(ctx context.Context, sampEnt *sampleentity.Sample)) *MockSampleEntityUsecaseInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sampleentity.Sample))
	})
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_Update_Call) Return(_a0 error) *MockSampleEntityUsecaseInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSampleEntityUsecaseInterface_Update_Call) RunAndReturn(run func(context.Context, *sampleentity.Sample) error) *MockSampleEntityUsecaseInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSampleEntityUsecaseInterface creates a new instance of MockSampleEntityUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSampleEntityUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSampleEntityUsecaseInterface {
	mock := &MockSampleEntityUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
