receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  debug:
    verbosity: detailed
    

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

processors:
  filter/drop_debug:
    error_mode: ignore
    logs:
      log_record:
        - 'severity_number < SEVERITY_NUMBER_INFO'
service:
  pipelines:
    logs:
      receivers: [otlp]
      # processors: [filter/drop_debug]
      exporters: [otlphttp, debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite, debug]
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo, debug]
