# See the dedicated "version" documentation section.
version: "2"

linters:
  default: fast
  enable:
    - canonicalheader
    - bodyclose
    - contextcheck
    - noctx
    - sqlclosecheck
    - misspell
    - errorlint
    - gocritic

  disable:
    - depguard
  exclusions:
    paths:
      - ^docs/.*
  

formatters:
  enable:
    - gofumpt
    - goimports
    - swaggo
