---
Tracing:
  Endpoint: "http://localhost:9411/api/v2/spans"
  ServiceName: "go-micro"
  SamplingRatio: 5
  Debug: true
  Enviorment: "dev"
  TURL: "https://www.google.com"

Server: 
  Port: "8080"
  Host: "0.0.0.0"
Redis: 
  Host: "127.0.0.1"
  Port: "6379"
  Password: ""
  DB: 0
  PoolSize: 100
  MinIdleConns: 10
  DialTimeout: 5
  ReadTimeout: 3
  WriteTimeout: 3
Mongo:
  Host: "127.0.0.1"
  Port: "27017"
  Username: ""
  Password: ""
  DB: "test"
  