openapi: 3.0.3
info:
  title: ""
  version: ""
paths:
  /api/sample/v1/sample_entities:
    get:
      description: List SampleEntity
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DtoSampleEntityResponse'
                type: array
          description: OK
      summary: List SampleEntity
      tags:
      - SampleEntity
    post:
      description: Create SampleEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DtoSampleEntityRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DtoSampleEntityResponse'
          description: OK
      summary: Create SampleEntity
      tags:
      - SampleEntity
  /healthz/liveness:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResponseString'
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResponseString'
          description: Internal Server Error
      summary: Healthz Liveness
      tags:
      - Healthz(Internal)
  /healthz/readiness:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResponseString'
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResponseString'
          description: Internal Server Error
      summary: Healthz Readiness
      tags:
      - Healthz(Internal)
components:
  schemas:
    DtoSampleEntityRequest:
      properties:
        name:
          type: string
        text:
          type: string
      type: object
    DtoSampleEntityResponse:
      properties:
        id:
          minimum: 0
          type: integer
        name:
          type: string
        text:
          type: string
      type: object
    ResponseResponseString:
      properties:
        data:
          type: string
        message:
          type: string
        status:
          type: integer
      type: object
