apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app:latest
        livenessProbe:
          httpGet: 
            path: /healthz/liveness
            port: 8080
        readinessProbe:
          httpGet: 
            path: /healthz/readiness
            port: 8080
        resources:
          limits:
            memory: "32Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
