// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthzRepoInterface is an autogenerated mock type for the HealthzRepoInterface type
type MockHealthzRepoInterface struct {
	mock.Mock
}

type MockHealthzRepoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthzRepoInterface) EXPECT() *MockHealthzRepoInterface_Expecter {
	return &MockHealthzRepoInterface_Expecter{mock: &_m.Mock}
}

// Liveness provides a mock function with given fields: ctx
func (_m *MockHealthzRepoInterface) Liveness(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Liveness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthzRepoInterface_Liveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Liveness'
type MockHealthzRepoInterface_Liveness_Call struct {
	*mock.Call
}

// Liveness is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthzRepoInterface_Expecter) Liveness(ctx interface{}) *MockHealthzRepoInterface_Liveness_Call {
	return &MockHealthzRepoInterface_Liveness_Call{Call: _e.mock.On("Liveness", ctx)}
}

func (_c *MockHealthzRepoInterface_Liveness_Call) Run(run func(ctx context.Context)) *MockHealthzRepoInterface_Liveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthzRepoInterface_Liveness_Call) Return(_a0 error) *MockHealthzRepoInterface_Liveness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthzRepoInterface_Liveness_Call) RunAndReturn(run func(context.Context) error) *MockHealthzRepoInterface_Liveness_Call {
	_c.Call.Return(run)
	return _c
}

// Readiness provides a mock function with given fields: ctx
func (_m *MockHealthzRepoInterface) Readiness(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Readiness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthzRepoInterface_Readiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readiness'
type MockHealthzRepoInterface_Readiness_Call struct {
	*mock.Call
}

// Readiness is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthzRepoInterface_Expecter) Readiness(ctx interface{}) *MockHealthzRepoInterface_Readiness_Call {
	return &MockHealthzRepoInterface_Readiness_Call{Call: _e.mock.On("Readiness", ctx)}
}

func (_c *MockHealthzRepoInterface_Readiness_Call) Run(run func(ctx context.Context)) *MockHealthzRepoInterface_Readiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthzRepoInterface_Readiness_Call) Return(_a0 error) *MockHealthzRepoInterface_Readiness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthzRepoInterface_Readiness_Call) RunAndReturn(run func(context.Context) error) *MockHealthzRepoInterface_Readiness_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthzRepoInterface creates a new instance of MockHealthzRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthzRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthzRepoInterface {
	mock := &MockHealthzRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
