// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/internal/biz"
	"application/internal/datasource"
	"application/internal/repo"
	"application/internal/service"
	"application/internal/service/handler"
	"application/pkg/initializer/config"
	"context"
	"github.com/swaggest/openapi-go/openapi3"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, cfg config.Config, logger *slog.Logger, oapi3r *openapi3.Reflector) (http.Handler, error) {
	oapi := service.NewOAPI(oapi3r, logger)
	inmemoryDB := datasource.NewInmemoryDB(logger)
	healthzRepoInterface := repo.NewHealthzDS(logger, inmemoryDB)
	healthzUseCaseInterface := biz.NewHealthzBiz(healthzRepoInterface, logger)
	healthzHandler := handler.NewMuxHealthzHandler(healthzUseCaseInterface, logger)
	buildingHandler := handler.NewMuxBuildingHandler(logger)
	movieHandler := handler.NewMuxMovieHandler(logger)
	seriesHandler := handler.NewMuxSeriesHandler(logger)
	channelHandler := handler.NewMuxChannelHandler(logger)
	v := handler.NewServiceList(healthzHandler, buildingHandler, movieHandler, seriesHandler, channelHandler)
	httpHandler, err := service.NewHTTPHandler(oapi3r, oapi, v...)
	if err != nil {
		return nil, err
	}
	return httpHandler, nil
}
