// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/app"
	"app/config"
	"app/internal/biz"
	"app/internal/data"
	"app/internal/service"
	"github.com/rs/zerolog"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

func wireApp(config2 *config.Config, logger zerolog.Logger, metricProvider metric.MeterProvider) (*app.App, func(), error) {
	dataData, cleanup, err := data.NewData(config2)
	if err != nil {
		return nil, nil, err
	}
	healthzRepo := data.NewHealthzRepo(dataData)
	healthzUsecase := biz.NewHealthzUsecase(healthzRepo, config2, logger)
	healthzService := service.NewHealthzService(healthzUsecase)
	serviceService := service.NewService(healthzService)
	appApp := app.NewApp(config2, serviceService)
	return appApp, func() {
		cleanup()
	}, nil
}
