// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/biz/sample/v1/sample_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/biz/sample/v1/sample_interfaces.go -destination=./mock/sample/v1/sample.go
//

// Package mock_sampleusecasev1 is a generated GoMock package.
package mock_sampleusecasev1

import (
	sampleentity "application/internal/entity/sample"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSampleEntityRepoInterface is a mock of SampleEntityRepoInterface interface.
type MockSampleEntityRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSampleEntityRepoInterfaceMockRecorder
}

// MockSampleEntityRepoInterfaceMockRecorder is the mock recorder for MockSampleEntityRepoInterface.
type MockSampleEntityRepoInterfaceMockRecorder struct {
	mock *MockSampleEntityRepoInterface
}

// NewMockSampleEntityRepoInterface creates a new mock instance.
func NewMockSampleEntityRepoInterface(ctrl *gomock.Controller) *MockSampleEntityRepoInterface {
	mock := &MockSampleEntityRepoInterface{ctrl: ctrl}
	mock.recorder = &MockSampleEntityRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSampleEntityRepoInterface) EXPECT() *MockSampleEntityRepoInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSampleEntityRepoInterface) Create(ctx context.Context, sampleEntity *sampleentity.Sample) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sampleEntity)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSampleEntityRepoInterfaceMockRecorder) Create(ctx, sampleEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSampleEntityRepoInterface)(nil).Create), ctx, sampleEntity)
}

// Delete mocks base method.
func (m *MockSampleEntityRepoInterface) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSampleEntityRepoInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSampleEntityRepoInterface)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockSampleEntityRepoInterface) List(ctx context.Context) ([]*sampleentity.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*sampleentity.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSampleEntityRepoInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSampleEntityRepoInterface)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockSampleEntityRepoInterface) Update(ctx context.Context, sampleEntity *sampleentity.Sample) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, sampleEntity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSampleEntityRepoInterfaceMockRecorder) Update(ctx, sampleEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSampleEntityRepoInterface)(nil).Update), ctx, sampleEntity)
}

// MockSampleEntityUsecaseInterface is a mock of SampleEntityUsecaseInterface interface.
type MockSampleEntityUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSampleEntityUsecaseInterfaceMockRecorder
}

// MockSampleEntityUsecaseInterfaceMockRecorder is the mock recorder for MockSampleEntityUsecaseInterface.
type MockSampleEntityUsecaseInterfaceMockRecorder struct {
	mock *MockSampleEntityUsecaseInterface
}

// NewMockSampleEntityUsecaseInterface creates a new mock instance.
func NewMockSampleEntityUsecaseInterface(ctrl *gomock.Controller) *MockSampleEntityUsecaseInterface {
	mock := &MockSampleEntityUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockSampleEntityUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSampleEntityUsecaseInterface) EXPECT() *MockSampleEntityUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSampleEntityUsecaseInterface) Create(ctx context.Context, sampEnt *sampleentity.Sample) (*sampleentity.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sampEnt)
	ret0, _ := ret[0].(*sampleentity.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSampleEntityUsecaseInterfaceMockRecorder) Create(ctx, sampEnt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSampleEntityUsecaseInterface)(nil).Create), ctx, sampEnt)
}

// Delete mocks base method.
func (m *MockSampleEntityUsecaseInterface) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSampleEntityUsecaseInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSampleEntityUsecaseInterface)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockSampleEntityUsecaseInterface) List(ctx context.Context) ([]*sampleentity.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*sampleentity.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSampleEntityUsecaseInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSampleEntityUsecaseInterface)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockSampleEntityUsecaseInterface) Update(ctx context.Context, sampEnt *sampleentity.Sample) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, sampEnt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSampleEntityUsecaseInterfaceMockRecorder) Update(ctx, sampEnt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSampleEntityUsecaseInterface)(nil).Update), ctx, sampEnt)
}
