definitions:
  response.Response-bool:
    properties:
      data:
        type: boolean
      message:
        type: string
      status:
        type: integer
    type: object
  response.Response-string:
    properties:
      data:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: info@aban.io
    name: API Support
    url: http://aban.io/support
  description: API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger
  version: "1.0"
paths:
  /healthz/liveness:
    get:
      consumes:
      - application/json
      description: Check the liveness of the service
      operationId: healthz-liveness
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/response.Response-bool'
      summary: Healthz Liveness
      tags:
      - healthz
  /healthz/panic:
    get:
      responses:
        "500":
          description: panic
          schema:
            $ref: '#/definitions/response.Response-string'
      summary: Panic for test
      tags:
      - healthz
  /healthz/rediness:
    get:
      consumes:
      - application/json
      description: Check the readiness of the service
      operationId: healthz-rediness
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/response.Response-string'
      summary: Healthz Readiness
      tags:
      - healthz
  /healthz/sleep/{time}:
    get:
      parameters:
      - description: Time to sleep, e.g. 30s
        in: path
        name: time
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/response.Response-string'
      summary: Long Run for test
      tags:
      - healthz
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
